CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE food
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(200)                            NOT NULL,
    calories    DOUBLE PRECISION,
    protein     DOUBLE PRECISION                        NOT NULL,
    carbs       DOUBLE PRECISION                        NOT NULL,
    fat         DOUBLE PRECISION                        NOT NULL,
    category_id BIGINT,
    CONSTRAINT pk_food PRIMARY KEY (id)
);

CREATE TABLE meal
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE,
    user_id   BIGINT,
    CONSTRAINT pk_meal PRIMARY KEY (id)
);

CREATE TABLE meal_item
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount  DOUBLE PRECISION,
    meal_id BIGINT,
    food_id BIGINT,
    CONSTRAINT pk_mealitem PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE food
    ADD CONSTRAINT FK_FOOD_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE meal_item
    ADD CONSTRAINT FK_MEALITEM_ON_FOOD FOREIGN KEY (food_id) REFERENCES food (id);

ALTER TABLE meal_item
    ADD CONSTRAINT FK_MEALITEM_ON_MEAL FOREIGN KEY (meal_id) REFERENCES meal (id);

ALTER TABLE meal
    ADD CONSTRAINT FK_MEAL_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);