CREATE TABLE goal (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      user_id BIGINT NOT NULL,

                      calories_target INTEGER NOT NULL,
                      protein_g INTEGER,
                      carbs_g INTEGER,
                      fat_g INTEGER,

                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                      CONSTRAINT pk_goal PRIMARY KEY (id),
                      CONSTRAINT uq_goal_user UNIQUE (user_id),
                      CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES users (id)
);
